#!/bin/bash

PROJECT=tiktokserver
ENV=dev

if [ $1 ]; then
    ENV=$1
fi

IMAGE_NAME_TEMPLATE=$PROJECT/$ENV

CONTAINER_ID=$(docker ps | grep "$IMAGE_NAME_TEMPLATE" | awk '{print $1}')
if [ ! -z $CONTAINER_ID ]; then
    echo "Found container to be connect to it's shell: "$CONTAINER_ID
    echo "Connecting to the container..."
    docker exec -it $CONTAINER_ID sh
    echo "The end!"
else
    echo "Application is not running!"
    echo "To run the application locally please execute: ./drunapp dev <version>"
fi

