#!/bin/bash

PROJECT=tiktokapi
VERSION=latest
ENV=dev

if [ $1 ]; then
    ENV=$1
fi

if [ $2 ]; then
    VERSION=$2
fi

IMAGE_NAME=$PROJECT/$ENV
IMAGE_URL=$IMAGE_NAME:$VERSION

docker push $IMAGE_URL