#!/bin/bash

PROJECT=tiktokapi
VERSION=latest
ENV=dev

if [ $1 ]; then
    ENV=$1
fi

if [ $2 ]; then
    VERSION=$2
fi

IMAGE_NAME=$PROJECT/$ENV

IMAGE_URL=$IMAGE_NAME:$VERSION

if [ $ENV = "prod" ]; then
    docker run -it -d \
        -p 8081:80 \
        --mount src=$(pwd)/environment/prod/docker/php/opcache.ini,target=/etc/php7/conf.d/opcache.ini,type=bind \
        --mount src=$(pwd)/environment/prod/docker/php/logging.ini,target=/etc/php7/conf.d/logging.ini,type=bind \
        --mount src=$(pwd)/environment/prod/docker/crontab,target=/tmp/crontab,type=bind \
        --mount src=$(pwd)/public,target=/var/www/html,type=bind \
        $IMAGE_URL
fi

if [ $ENV = "dev" ]; then
    docker run -it -d \
        -p 8081:80 \
        -e PHP_IDE_CONFIG="serverName=tiktok" \
        -e PHP_XDEBUG_ENABLED=1 \
        -e XDEBUG_CONFIG="remote_host=172.17.0.1;idekey=phpstorm" \
        --network="bridge" \
        --mount src=$(pwd)/environment/dev/docker/php/xdebug-common.ini,target=/etc/php7/conf.d/xdebug.ini,type=bind \
        --mount src=$(pwd)/environment/dev/docker/php/opcache.ini,target=/etc/php7/conf.d/opcache.ini,type=bind \
        --mount src=$(pwd)/environment/prod/docker/php/logging.ini,target=/etc/php7/conf.d/logging.ini,type=bind \
        --mount src=$(pwd)/environment/prod/docker/crontab,target=/tmp/crontab,type=bind \
        --mount src=$(pwd)/public,target=/var/www/html,type=bind \
        $IMAGE_URL
fi

